# Generated by Django 2.1.7 on 2019-03-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsong', '0002_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texte',
            name='paroles',
            field=models.TextField(max_length=3000),
        ),
    ]
