# Generated by Django 2.1.7 on 2019-03-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsong', '0003_auto_20190316_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texte',
            name='paroles',
            field=models.TextField(max_length=5000),
        ),
    ]
