# Generated by Django 2.1.7 on 2019-03-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texte',
            fields=[
                ('chanson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appsong.Chanson')),
                ('paroles', models.TextField(max_length=1000)),
            ],
        ),
    ]
